### ISSUE TITLE
TypeError: cli.isMultipleCompiler is not a function

### ISSUE THREAD

**Issue by 7flash** [dfinity/sdk#2329]
Initialized a new app with "dfx start".. trying to start in dev mode after "npm install"..

![image](https://user-images.githubusercontent.com/4569866/178142204-5a381dfd-97b9-4d8a-82e3-63bd4394aee4.png)

**Comment by sesi200** [comment]
Seems to work with the latest beta (0.12.0-beta.3). Feel free to reopen if this is still an issue.
