### ISSUE TITLE
Error when accessing frontend in 0.5.5

### ISSUE THREAD

**Issue by alexabsmith** [dfinity/sdk#549]
From Zendesk:

After upgrading to 0.5.5 im getting this error when trying to access the canister frontend. I’m on macOS 10.13.6. I already deleted .dfx/state in the project direcotry and reinstalled dfx.

Also dfx throws errors, even though the canister was installed correctly:

Apr 05 23:02:29.381 WARN Could not perform query on canister: IC0301: Canister ic:B5008CEB5C40C41D42 not found, Application: Http Handler

```
An error happened:
TypeError: e.Service is not a function
    at t.default (data:text/javascript;base64,LyohIEZvciBsaWNlbnNlIGluZm9ybWF0aW9uIHBsZWFzZSBzZWUgaW5kZXguanMuTElDRU5TRSAqLwohZnVuY3Rpb24oZSl7dmFyIHQ9e307ZnVuY3Rpb24gbihyKXtpZih0W3JdKXJldHVybiB0W3JdLmV4cG9ydHM7dmFyIGw9dFtyXT17aTpyLGw6ITEsZXhwb3J0czp7fX07cmV0dXJuIGVbcl0uY2FsbChsLmV4cG9ydHMsbCxsLmV4cG9ydHMsbiksbC5sPSEwLGwuZXhwb3J0c31uLm09ZSxuLmM9dCxuLmQ9ZnVuY3Rpb24oZSx0LHIpe24ubyhlLHQpfHxPYmplY3QuZGVmaW5lUHJvcGVydHkoZSx0LHtlbnVtZXJhYmxlOiEwLGdldDpyfSl9LG4ucj1mdW5jdGlvbihlKXsidW5kZWZpbmVkIiE9dHlwZW9mIFN5bWJvbCYmU3ltYm9sLnRvU3RyaW5nVGFnJiZPYmplY3QuZGVmaW5lUHJvcGVydHkoZSxTeW1ib2wudG9TdHJpbmdUYWcse3ZhbHVlOiJNb2R1bGUifSksT2JqZWN0LmRlZmluZVByb3BlcnR5KGUsIl9fZXNNb2R1bGUiLHt2YWx1ZTohMH0pfSxuLnQ9ZnVuY3Rpb24oZSx0KXtpZigxJnQmJihlPW4oZSkpLDgmdClyZXR1cm4gZTtpZig0JnQmJiJvYmplY3QiPT10eXBlb2YgZSYmZSYmZS5fX2VzTW9kdWxlKXJldHVybiBlO3ZhciByPU9iamVjdC5jcmVhdGUobnVsbCk7aWYobi5yKHIpLE9iamVjdC5kZWZpbmVQcm9wZXJ0eShyLCJkZWZhdWx0Iix7ZW51bWVyYWJsZTohMCx2YWx1ZTplfSksMiZ0JiYic3RyaW5nIiE9dHlwZW9mIGUpZm9yKHZhciBsIGluIGUpbi5kKHIsbCxmdW5jdGlvbih0KXtyZXR1cm4gZVt0XX0uYmluZChudWxsLGwpKTtyZXR1cm4gcn0sbi5uPWZ1bmN0aW9uKGUpe3ZhciB0PWUmJmUuX19lc01vZHVsZT9mdW5jdGlvbigpe3JldHVybiBlLmRlZmF1bHR9OmZ1bmN0aW9uKCl7cmV0dXJuIGV9O3JldHVybiBuLmQodCwiYSIsdCksdH0sbi5vPWZ1bmN0aW9uKGUsdCl7cmV0dXJuIE9iamVjdC5wcm90b3R5cGUuaGFzT3duUHJvcGVydHkuY2FsbChlLHQpfSxuLnA9IiIsbihuLnM9Mil9KFtmdW5jdGlvbihlLHQsbil7InVzZSBzdHJpY3QiO2UuZXhwb3J0cz1uKDUpfSxmdW5jdGlvbihlLHQsbil7InVzZSBzdHJpY3QiO3ZhciByPU9iamVjdC5nZXRPd25Qcm9wZXJ0eVN5bWJvbHMsbD1PYmplY3QucHJvdG90eXBlLmhhc093blByb3BlcnR5LGk9T2JqZWN0LnByb3RvdHlwZS5wcm9wZXJ0eUlzRW51bWVyYWJsZTtmdW5jdGlvbiBhKGUpe2lmKG51bGw9PWUpdGhyb3cgbmV3IFR5cGVFcnJvcigiT2JqZWN0LmFzc2lnbiBjYW5ub3QgYmUgY2FsbGVkIHdpdGggbnVsbCBvciB1bmRlZmluZWQiKTtyZXR1cm4gT2JqZWN0KGUpfWUuZXhwb3J0cz1mdW5jdGlvbigpe3RyeXtpZighT2JqZWN0LmFzc2lnbilyZXR1cm4hMTt2YXIgZT1uZXcgU3RyaW5nKCJhYmMiKTtpZihlWzVdPSJkZSIsIjUiPT09T2JqZWN0LmdldE93blByb3BlcnR5TmFtZXMoZSlbMF0pcmV0dXJuITE7Zm9yKHZhciB0PXt9LG49MDtuPDEwO24rKyl0WyJfIitTdHJpbmcuZnJvbUNoYXJDb2RlKG4pXT1uO2lmKCIwMTIzNDU2Nzg5IiE9PU9iamVjdC5nZXRPd25Qcm9wZXJ0eU5hbWVzKHQpLm1hcCgoZnVuY3Rpb24oZSl7cmV0dXJuIHRbZV19KSkuam9pbigiIikpcmV0dXJuITE7dmFyIHI9e307cmV0dXJuImFiY2RlZmdoaWprbG1ub3BxcnN0Ii5zcGxpdCgiIikuZm9yRWFjaCgoZnVuY3Rpb24oZSl7cltlXT1lfSkpLCJhYmNkZWZnaGlqa2xtbm9wcXJzdCI9PT1PYmplY3Qua2V5cyhPYmplY3QuYXNzaWduKHt9LHIpKS5qb2luKCIiKX1jYXRjaChlKXtyZXR1cm4hMX19KCk/T2JqZWN0LmFzc2lnbjpmdW5jdGlvbihlLHQpe2Zvcih2YXIgbixvLHU9YShlKSxjPTE7Yzxhcmd1bWVudHMubGVuZ3RoO2MrKyl7Zm9yKHZhciBzIGluIG49T2JqZWN0KGFyZ3VtZW50c1tjXSkpbC5jYWxsKG4scykmJih1W3NdPW5bc10pO2lmKHIpe289cihuKTtmb3IodmFyIGY9MDtmPG8ubGVuZ3RoO2YrKylpLmNhbGwobixvW2ZdKSYmKHVbb1tmXV09bltvW2ZdXSl9fXJldHVybiB1fX0sZnVuY3Rpb24oZSx0LG4peyJ1c2Ugc3RyaWN0IjtPYmplY3QuZGVmaW5lUHJvcGVydHkodCwiX19lc01vZHVsZSIse3ZhbHVlOiEwfSk7Y29uc3Qgcj1uKDMpLGw9bigwKSxpPW4oNik7bigxMCk7Y2xhc3MgYSBleHRlbmRzIGwuQ29tcG9uZW50e2NvbnN0cnVjdG9yKGUpe3N1cGVyKGUpLHRoaXMuc3RvcHBlZD0hMSx0aGlzLnN0YXRlPXt9fWFzeW5jIGRvUG9wdWxhdGUoKXtsZXQgZT1kb2N1bWVudC5nZXRFbGVtZW50QnlJZCgibmV3RW50cnlXaWR0aCIpLnZhbHVlLHQ9ZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoIm5ld0VudHJ5SGVpZ2h0IikudmFsdWU7ci5kZWZhdWx0LnBvcHVsYXRlKHBhcnNlSW50KGUsMTApLHBhcnNlSW50KHQsMTApKX1hc3luYyBnZXRVbml2ZXJzZSgpe2RvY3VtZW50LmdldEVsZW1lbnRCeUlkKCJuZXdFbnRyeVdpZHRoIikudmFsdWU9cGFyc2VJbnQoYXdhaXQgci5kZWZhdWx0LmdldF93aWR0aCgpLDEwKSxkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgibmV3RW50cnlIZWlnaHQiKS52YWx1ZT1wYXJzZUludChhd2FpdCByLmRlZmF1bHQuZ2V0X2hlaWdodCgpLDEwKX1hc3luYyBkb1N0YXJ0KCl7ci5kZWZhdWx0LnN0YXJ0KCl9YXN5bmMgZG9SZW5kZXIoKXtjb25zdCBlPWRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCJnYW1lLW9mLWxpZmUtY2FudmFzIiksdD1hc3luYygpPT57ZS50ZXh0Q29udGVudD1hd2FpdCByLmRlZmF1bHQucmVuZGVyKCk7bGV0IG49YXdhaXQgci5kZWZhdWx0LmdldF91bml2ZXJzZSgpLGw9YXdhaXQgci5kZWZhdWx0LnRpY2soKTt0aGlzLnJlcUlkPXJlcXVlc3RBbmltYXRpb25GcmFtZSh0KSxKU09OLnN0cmluZ2lmeShuKSE9SlNPTi5zdHJpbmdpZnkobCkmJjEhPXRoaXMuc3RvcHBlZHx8Y2FuY2VsQW5pbWF0aW9uRnJhbWUodGhpcy5yZXFJZCl9O3JlcXVlc3RBbmltYXRpb25GcmFtZSh0KSx0aGlzLnN0b3BwZWQ9ITF9YXN5bmMgc3RvcFJlbmRlcigpe3RoaXMuc3RvcHBlZD0hMH1hc3luYyByZW5kZXJDdXJyZW50KCl7ZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoImdhbWUtb2YtbGlmZS1jYW52YXMiKS50ZXh0Q29udGVudD1hd2FpdCByLmRlZmF1bHQucmVuZGVyKCl9cmVuZGVyKCl7cmV0dXJuIGwuY3JlYXRlRWxlbWVudCgiZGl2Iix7Y2xhc3NOYW1lOiJuZXctZW50cnkifSxsLmNyZWF0ZUVsZW1lbnQoImRpdiIsbnVsbCxsLmNyZWF0ZUVsZW1lbnQoImgxIixudWxsLCJHYW1lIG9mIExpZmUiKSxsLmNyZWF0ZUVsZW1lbnQoImRpdiIsbnVsbCwiUG9wdWxhdGUgdGhlIHVuaXZlcnNlOiIsbC5jcmVhdGVFbGVtZW50KCJ0YWJsZSIsbnVsbCxsLmNyZWF0ZUVsZW1lbnQoInRyIixudWxsLGwuY3JlYXRlRWxlbWVudCgidGQiLG51bGwsIldpZHRoOiIpLGwuY3JlYXRlRWxlbWVudCgidGQiLG51bGwsbC5jcmVhdGVFbGVtZW50KCJpbnB1dCIse2lkOiJuZXdFbnRyeVdpZHRoIn0pKSksbC5jcmVhdGVFbGVtZW50KCJ0ciIsbnVsbCxsLmNyZWF0ZUVsZW1lbnQoInRkIixudWxsLCJIZWlnaHQ6IiksbC5jcmVhdGVFbGVtZW50KCJ0ZCIsbnVsbCxsLmNyZWF0ZUVsZW1lbnQoImlucHV0Iix7aWQ6Im5ld0VudHJ5SGVpZ2h0In0pKSkpLGwuY3JlYXRlRWxlbWVudCgiYnV0dG9uIix7b25DbGljazooKT0+dGhpcy5kb1B
```
Note: full error sent to @hansl
